hsn_client_path: /home/ubuntu/workplace/hschain/build/hsncli
hsn_server_path: /home/ubuntu/workplace/hschain/build/hsnd
hsn_local_account_path: /home/ubuntu/hsnhub_test
chain_id: hsn
unsign_dir: 
broadcasted_tx_dir: 
node_lcd_server: http://172.16.0.60:1317
node_rpc_server: http://172.16.0.60:26657
local_accounts_path: 